import { ROUTE_PATHS } from "@/routes/paths";

export const ONBOARDING_STEP_GROUPS = [
  [ROUTE_PATHS.ONBOARDING_BASIC_INFO],
  [ROUTE_PATHS.ONBOARDING_RELIGIOUS_LIFESTYLE, ROUTE_PATHS.ONBOARDING_RELIGIOUS_LIFESTYLE_STEP_2],
  [ROUTE_PATHS.ONBOARDING_PERSONALITY_STEP_3],
  [ROUTE_PATHS.ONBOARDING_FAMILY_STEP_4],
  [ROUTE_PATHS.ONBOARDING_STATUS_FEMALE_STEP_5, ROUTE_PATHS.ONBOARDING_STATUS_COHEN_MALE],
  [ROUTE_PATHS.ONBOARDING_MATCH_PREFERENCES_STEP_6],
  [ROUTE_PATHS.ONBOARDING_PHOTOS_REVIEW]
];

export const getOnboardingStepIndex = (pathname) =>
  ONBOARDING_STEP_GROUPS.findIndex((group) => group.includes(pathname));
